### ISSUE TITLE
Generate .stp file 

### ISSUE THREAD

**Issue by tdurieux** [gbl/D7CReader#3]
Hello,

First, thanks for your awesome reverse-engineering! 

I would like to generate a pattern and generate .stp file. Based on your experience, would it be difficult to adapt your code to be able to do that?

Thanks

**Comment by gbl** [comment]
It's been quite a while since I worked on this. But if I remember correctly, my software reads some of the data from the file; I haven't decoded the meaning of every byte.

Ignoring bytes from the file is ok when you just read the file, but to create a file, the meaning of all of them would still need to be found out, then the software would have to fill them correctly when writing something. So I assume writing those files would still be a considerable effort.

Maybe there are file formats that are documented and easier to write, which the software can import? That might be an easier route to go.

**Comment by tdurieux** [comment]
Thanks for the feedback!
